# Generated by Django 4.1.4 on 2023-02-03 12:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dkfgh093c/image/upload/v1675368559/user-default_m9kpsk.png', max_length=255, null=True),
        ),
    ]
