# Generated by Django 4.1.4 on 2023-01-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='source_code',
            new_name='source_link',
        ),
    ]
