# Generated by Django 4.1.4 on 2023-02-03 12:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_img',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dkfgh093c/image/upload/v1675368588/default_fsuwsb.jpg', max_length=255, null=True, verbose_name='images'),
        ),
    ]
