version: "3.11.1"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ".:/code"
    env_file:
      - "./.env.dev"
    depends_on:
      - db


  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - "./.env.dev.db"


volumes:
  postgres_data:
