# Generated by Django 4.1.4 on 2023-01-01 14:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('demo_link', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('source_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('featured_img', models.ImageField(blank=True, default='photos/projects/default.jpg', null=True, upload_to='photos/projects')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='profiles.profile')),
            ],
            options={
                'ordering': ['-updated_on', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=4)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='project.project')),
            ],
            options={
                'ordering': ['-updated_on', '-created_on'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='project.tag'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['id', '-updated_on', '-created_on'], name='project_rev_id_57869b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['id', '-updated_on', '-created_on'], name='project_pro_id_6e87a6_idx'),
        ),
    ]
